### ISSUE TITLE
Oui.txt error

### ISSUE THREAD

**Issue by 0x-MRNOBODY-x0** [alexxy/netdiscover#17]
$ sh http://standards-oui.ieee.org/oui/oui.txt
sh: 0: Can't open http://standards-oui.ieee.org/oui/oui.txt
$ nano update-oui-database.sh
$ nano update-oui-database.sh
$ sh update-oui-database.sh
Trying download "oui.txt" with lynx...update-oui-database.sh: 53: update-oui-database.sh: [[: not found
 with elinks...update-oui-database.sh: 57: update-oui-database.sh: [[: not found
 with wget...
update-oui-database.sh: 61: update-oui-database.sh: [[: not found
update-oui-database.sh: Can't obtain "http://standards-oui.ieee.org/oui/oui.txt"!
$ sh update-oui-database.sh
Trying download "oui.txt" with lynx...update-oui-database.sh: 53: update-oui-database.sh: [[: not found
 with elinks...update-oui-database.sh: 57: update-oui-database.sh: [[: not found
 with wget...
update-oui-database.sh: 61: update-oui-database.sh: [[: not found
update-oui-database.sh: Can't obtain "http://standards-oui.ieee.org/oui/oui.txt"!
$ nano update-oui-database.sh
$ sh update-oui-database.sh
Trying download "oui.txt" with lynx...update-oui-database.sh: 53: update-oui-database.sh: [[: not found
 with elinks...update-oui-database.sh: 57: update-oui-database.sh: [[: not found
 with wget...
update-oui-database.sh: 61: update-oui-database.sh: [[: not found
update-oui-database.sh: Can't obtain "http://standards-oui.ieee.org/oui/oui.h"!
$ nano update-oui-database.sh
$ sh update-oui-database.sh
Trying download "oui.txt" with lynx...update-oui-database.sh: 54: update-oui-database.sh: [[: not found
 with elinks...update-oui-database.sh: 58: update-oui-database.sh: [[: not found
 with wget...
update-oui-database.sh: 62: update-oui-database.sh: [[: not found
update-oui-database.sh: Can't obtain "https://raw.githubusercontent.com/alexxy/netdiscover/c74f29ccc83f8161136e5392fed30015bb475040/src/oui.h"!
$

I changed the link as -

http://standards-oui.ieee.org/oui/oui.h

http://standards-oui.ieee.org/oui/oui.txt

https://raw.githubusercontent.com/alexxy/netdiscover/c74f29ccc83f8161136e5392fed30015bb475040/src/oui.h

and tried so many times but didn't worked

**Comment by squallgold** [comment]
i update it manule.
[oui.txt](https://github.com/alexxy/netdiscover/files/3775598/oui.txt)
