### ISSUE TITLE
how make in mac os 10.12?

### ISSUE THREAD

**Issue by hktalent** [alexxy/netdiscover#2]
$ brew list
aescrypt        gdk-pixbuf      libnet          pygobject
aescrypt-packetizer geoip           libpcap         pygtk
aespipe         geoipupdate     libpng          python
aircrack-ng     gettext         libtiff         rbenv
ant         glib            libtool         readline
asio            gmp         libtorrent-rasterbar    reaver
atk         go          libxml2         redis
autoconf        gobject-introspection   libyaml         ruby
automake        grep            luajit          ruby-build
bdw-gc          gtk+            lynis           ruby21
boost           hadoop          lynx            scons
boost-python        harfbuzz        lzo         shared-mime-info
cairo           hbase           make            skipfish
cctools         hicolor-icon-theme  makedepend      slowhttptest
cloc            hping           maven           snappy
cmake           httrack         mongodb         snort
couchdb         hydra           mpfr            solr
cpp-netlib      icu4c           mysql           sonar
cryptopp        ilmbase         net-snmp        sonar-runner
curl            instantclient-basic nmap            sonarqube
daq         instantclient-sdk   node            spidermonkey
eigen           instantclient-sqlplus   nspr            sqlite
erlang          isl         numpy           suricata
ettercap        john-jumbo      opencv          tesseract
exiftool        jpeg            openexr         theharvester
exiv2           json-c          openssl         tor
fdupes          leptonica       pango           v8-315
findutils       libdnet         pcap            w3m
fontconfig      libevent        pcre            wget
fping           libffi          pixman          wrk
freetype        libgpg-error        pkg-config      wxmac
gawk            libidn          portaudio       xctool
gawk3           libksba         postgresql      xz
gcc         libmagic        py2cairo        zmap
gdbm            libmpc          pyenv

$ pwd
/project/netdiscover/src

$ which wget
/usr/local/bin/wget
$ which lynx
/usr/local/bin/lynx
$ sh update-oui-database.sh
-n Trying download "oui.txt" with lynx...
-n  with elinks...
 with wget...
update-oui-database.sh: Can't obtain "http://standards.ieee.org/regauth/oui/oui.txt"!

$ make
$ make
[ 11%] Building C object CMakeFiles/netdiscover.dir/main.o
In file included from /Volumes/BOOK/安全/project/netdiscover/src/main.c:39:
/Volumes/BOOK/安全/project/netdiscover/src/ifaces.h:38:10: fatal error: 
      'netinet/ether.h' file not found
# include <netinet/ether.h>

```
     ^
```

1 error generated.
make[2]: **\* [CMakeFiles/netdiscover.dir/main.o] Error 1
make[1]: **\* [CMakeFiles/netdiscover.dir/all] Error 2
make: **\* [all] Error 2

**Comment by aachi-yang** [comment]
For MAC, I do a patch but not good to issue pull request yet, but you still can get it through.

https://github.com/aachi-yang/netdiscover

In the repo:
mkdir -p build
cd build
cmake ..
make

**Comment by VirusMachine** [comment]
@aachi-yang Great Work Buddy.. Worked Fine

**Comment by guipdutra** [comment]
Thanks @aachi-yang, worked fine
